// Windows build tool only. Applications use the generated bytecode source.
#include <windows.h>
#include <d3dcompiler.h>
#include <fstream>
#include <iterator>
#include <string>
#include <cstdio>
int main(int argc,char **argv) {
    if(argc!=3)return 1;
    std::ifstream in(argv[1]);
    if(!in)return 1;
    std::string source((std::istreambuf_iterator<char>(in)),std::istreambuf_iterator<char>());
    ID3DBlob *code=NULL,*errors=NULL;
    HRESULT hr=D3DCompile(source.data(),source.size(),"draw.hlsl",NULL,NULL,"main","ps_2_0",
        D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code,&errors);
    if(errors){fwrite(errors->GetBufferPointer(),1,errors->GetBufferSize(),stderr);errors->Release();}
    if(FAILED(hr))return 1;
    FILE *out=fopen(argv[2],"wb");if(!out){code->Release();return 1;}
    fprintf(out,"// Generated from shaders/draw.hlsl by shaders/compile.cpp.\n#include <windows.h>\nextern const DWORD m2d9_draw_shader[] = {\n");
    const DWORD *p=(const DWORD *)code->GetBufferPointer();
    for(size_t i=0;i<code->GetBufferSize()/4;++i)fprintf(out,"0x%08lx,%s",(unsigned long)p[i],(i%6==5||i+1==code->GetBufferSize()/4)?"\n":" ");
    fprintf(out,"};\n");fclose(out);code->Release();return 0;
}
