"""Embed checked-in shader assets; run after compiling SPIR-V/DXBC."""
from pathlib import Path
import json
root = Path(__file__).resolve().parent
out = ["/* Generated by shaders/embed.py. */", "#include <stddef.h>"]
out.append("static const char gpu_metal[] = " + json.dumps((root / "draw.metal").read_text()) + ";")
for stage in ("vert", "frag"):
    data = (root / ("draw." + stage + ".spv")).read_bytes()
    name = "gpu_" + stage + "_spv"
    out.append("static const unsigned char " + name + "[] = {\n" + ",".join(str(x) for x in data) + "\n};")
(root.parent / "shaders.h").write_text("\n".join(out) + "\n")
